# FFT params
n_fft: 2048
hop_length: 1024
num_frame: 128

# SVS Framework
spec_type: 'complex'
spec_est_mode: 'mapping'

# Other Hyperparams
optimizer: 'adam'
lr: 0.001
dev_mode: False
train_loss: 'spec_mse'
val_loss: 'raw_l1'

# DenseNet Hyperparams

n_blocks: 7
input_channels: 4
internal_channels: 24
first_conv_activation: 'relu'
last_activation: 'identity'
t_down_layers: ~
f_down_layers: ~
tif_init_mode: ~

# TFC_TDF Block's Hyperparams
n_internal_layers: 5
kernel_size_t: 3
kernel_size_f: 3
tfc_tdf_activation: 'relu'
bn_factor: 16
min_bn_units: 16
tfc_tdf_bias: True
num_tdfs: 6
dk: 32

control_vector_type: 'embedding'
control_input_dim: 4
embedding_dim: 32
condition_to: 'decoder'

control_n_layer: 4
control_type: 'dense'
pocm_type: 'matmul'
pocm_norm: 'batch_norm'